### ISSUE TITLE
NodeJS+MongoDB problem

### ISSUE THREAD

**Issue by Testato** [c9s/typeloy#43] opened 2016-10-09 13:37 UTC
Remote VPS Ubuntu16-64bit
Local PC Xubuntu16-32bit

on Typeloy 1.6.6 there is two problem:
1) the NodeJS installed is always ver 0.10.44 (instead i set 4.6.0 on typeloy.json)
2) The MongoDB installation FAIL

```
xubuntu@xubuntu-VirtualBox:~/Desktop/testapp$ typeloy setup MeteorVPS
Found /home/xubuntu/Desktop/testapp/settings.json

Started TaskList: Setup Tasks
[xxx] - Updating package index
[xxx] - Updating package index: SUCCESS
[xxx] - Installing Node.js: 0.10.44
[xxx] - Installing Node.js: 0.10.44: SUCCESS
[xxx] - Setting up environment for meteor application
[xxx] - Setting up environment for meteor application: SUCCESS
[xxx] - Setting up shared bash functions
[xxx] - Setting up shared bash functions: SUCCESS
[xxx] - Copying MongoDB configuration
[xxx] - Copying MongoDB configuration: SUCCESS
[xxx] - Installing MongoDB
[xxx] x Installing MongoDB: FAILED

    -----------------------------------STDERR-----------------------------------
    gpg: requesting key EA312927 from hkp server keyserver.ubuntu.com
    gpg: key EA312927: "MongoDB 3.2 Release Signing Key <packaging@mongodb.com>" not changed
    gpg: Total number processed: 1
    gpg:              unchanged: 1
    debconf: unable to initialize frontend: Dialog
    debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
    debconf: falling back to frontend: Readline
    debconf: unable to initialize frontend: Readline
    debconf: (This frontend requires a controlling tty.)
    debconf: falling back to frontend: Teletype
    dpkg-preconfigure: unable to re-open stdin: 
    bash: line 31: /lib/systemd/system/mongod.service: Permission denied
    -----------------------------------STDOUT-----------------------------------
    ion (3.2.10).
    The following packages will be upgraded:
      mongodb-org
    1 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
    Need to get 0 B/3,556 B of archives.
    After this operation, 12.3 kB of additional disk space will be used.
(Reading database ... 120258 files and directories currently installed.)
    Preparing to unpack .../mongodb-org_3.2.10_amd64.deb ...
    Unpacking mongodb-org (3.2.10) over (3.2.10) ...
    Setting up mongodb-org (3.2.10) ...
    ----------------------------------------------------------------------------
```

**Comment by c9s** [comment] 2016-10-09 13:54
I think this can be solved by using `export DEBIAN_FRONTEND=noninteractive`

**Comment by c9s** [comment] 2016-10-09 13:54
@Testato  fixed. can you try this one?

**Comment by c9s** [comment] 2016-10-09 13:55
updated in v1.6.7

**Comment by Testato** [comment] 2016-10-09 14:06
Nope, same problem, exactly same errorlog

**Comment by c9s** [comment] 2016-10-09 14:31
@Testato I can't reproduce this. but could you please try 34a82f0 ? it seems sudo don't read the env vars?

**Comment by c9s** [comment] 2016-10-09 14:32
What if you run this on the server in your terminal?

```
    sudo DEBIAN_FRONTEND=noninteractive apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
```

**Comment by c9s** [comment] 2016-10-09 14:33
oh I found the issue

**Comment by c9s** [comment] 2016-10-09 14:35
Try 8b44b4c

**Comment by Testato** [comment] 2016-10-09 15:01
Now it different, fail on service installation
Debconf error maybe is only a warning ? we can live whit it ?

```
x Installing MongoDB: FAILED

    -----------------------------------STDERR-----------------------------------
    gpg: requesting key EA312927 from hkp server keyserver.ubuntu.com
    gpg: key EA312927: "MongoDB 3.2 Release Signing Key <packaging@mongodb.com>" not changed
    gpg: Total number processed: 1
    gpg:              unchanged: 1
    debconf: unable to initialize frontend: Dialog
    debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
    debconf: falling back to frontend: Readline
    debconf: unable to initialize frontend: Readline
    debconf: (This frontend requires a controlling tty.)
    debconf: falling back to frontend: Teletype
    dpkg-preconfigure: unable to re-open stdin: 
    Failed to stop .service.service: Unit .service.service not loaded.
    Failed to start mongo.service: Unit mongo.service not found.
    -----------------------------------STDOUT-----------------------------------
(Reading database ... 120333 files and directories currently installed.)
    Preparing to unpack .../mongodb-org_3.2.10_amd64.deb ...
    Unpacking mongodb-org (3.2.10) over (3.2.10) ...
    Setting up mongodb-org (3.2.10) ...
    [Unit]
    Description=High-performance, schema-free document-oriented database
    After=network.target
    Documentation=https://docs.mongodb.org/manual

    [Service]
    User=mongodb
    Group=mongodb
    ExecStart=/usr/bin/mongod --quiet --config /etc/mongod.conf

    [Install]
    WantedBy=multi-user.target
    ----------------------------------------------------------------------------

```

**Comment by c9s** [comment] 2016-10-09 15:02
Yes. its caused by the incorrect service entry

**Comment by c9s** [comment] 2016-10-10 06:57
Fixed in 85db505

**Comment by Testato** [comment] 2016-10-10 07:06
I will test it this afternoon.

For the NodeJS problem what do you think ?

**Comment by c9s** [comment] 2016-10-10 07:30
The node version issue should be fixed in e3c9704

**Comment by Testato** [comment] 2016-10-10 12:17
Yep, now is installed the nodejs specified, but the mongod service error continue:
```
Started TaskList: Setup Tasks
[xxx] - Updating package index
[xxx] - Updating package index: SUCCESS
[xxx] - Installing Node.js: 4.6.0
[xxx] - Installing Node.js: 4.6.0: SUCCESS
[xxx] - Setting up environment for meteor application
[xxx] - Setting up environment for meteor application: SUCCESS
[xxx] - Setting up shared bash functions
[xxx] - Setting up shared bash functions: SUCCESS
[xxx] - Copying MongoDB configuration
[xxx] - Copying MongoDB configuration: SUCCESS
[xxx] - Installing MongoDB
[xxx] x Installing MongoDB: FAILED
	
	-----------------------------------STDERR-----------------------------------
	gpg: requesting key EA312927 from hkp server keyserver.ubuntu.com
	gpg: key EA312927: "MongoDB 3.2 Release Signing Key <packaging@mongodb.com>" not changed
	gpg: Total number processed: 1
	gpg:              unchanged: 1
	debconf: unable to initialize frontend: Dialog
	debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
	debconf: falling back to frontend: Readline
	debconf: unable to initialize frontend: Readline
	debconf: (This frontend requires a controlling tty.)
	debconf: falling back to frontend: Teletype
	dpkg-preconfigure: unable to re-open stdin: 
	Failed to stop mongo.service: Unit mongo.service not loaded.
	Failed to start mongo.service: Unit mongo.service not found.
	-----------------------------------STDOUT-----------------------------------
(Reading database ... 120333 files and directories currently installed.)
	Preparing to unpack .../mongodb-org_3.2.10_amd64.deb ...
	Unpacking mongodb-org (3.2.10) over (3.2.10) ...
	Setting up mongodb-org (3.2.10) ...
	[Unit]
	Description=High-performance, schema-free document-oriented database
	After=network.target
	Documentation=https://docs.mongodb.org/manual
	
	[Service]
	User=mongodb
	Group=mongodb
	ExecStart=/usr/bin/mongod --quiet --config /etc/mongod.conf
	
	[Install]
	WantedBy=multi-user.target
	----------------------------------------------------------------------------

```

**Comment by Testato** [comment] 2016-10-10 13:15
sorry the nodejs continue to have problem:
i removed nodejs and mongodb that i had manually installed and tried install by Typeloy, i set node 4.4.7 on typeloy.json

```
Started TaskList: Setup Tasks
[xxx] - Updating package index
[xxx] - Updating package index: SUCCESS
[xxx] - Installing Node.js: 4.4.7
[xxx] x Installing Node.js: 4.4.7: FAILED

    -----------------------------------STDERR-----------------------------------
     11850K .......... .......... .......... .......... .......... 99%  198M 0s
     11900K ....                                                  100% 7896G=0.9s

    2016-10-10 09:11:51 (12.5 MB/s) - ‘node-v4.4.7-linux-x64.tar.gz’ saved [12189839/12189839]

    /usr/local/bin/npm: 2: exec: /usr/local/bin/node: not found
    ----------------------------------------------------------------------------

```

**Comment by Testato** [comment] 2016-10-10 13:29
I found the problem, typeloy install Node to
`/usr/bin/node`
But after he search it on another dir
`/usr/local/bin/node: not found`

**Comment by c9s** [comment] 2016-10-10 13:45
this is weird I dont have this kid of error on a new server.

Testato notifications@github.com 於 2016年10月10日 星期一寫道：

**Comment by Testato** [comment] 2016-10-10 13:50
are you tried remove the nodejs completely ? 
Befoure Typeloy setup, your server must respond in this way:

```
testatovps@ubuntu:~$ node -v
-bash: /usr/bin/node: No such file or directory
```

I tell this because i had a node 4.6.0 manually installed to /usr/local/bin/node, and so typeloy do not found any problem, because it Install a second Node to /usr/bin/node and after he use the ones in /usr/local/bin/node

**Comment by c9s** [comment] 2016-10-10 13:54
The server doesn't  have any manually installed node before setup.

**Comment by c9s** [comment] 2016-10-10 13:56
will check your log later

**Comment by c9s** [comment] 2016-10-10 14:01
https://github.com/c9s/typeloy/blob/master/scripts/linux/install-node.sh here is the installer.

**Comment by Testato** [comment] 2016-10-10 16:28
OK whit the actual Master node and mongo install rpoblem is solved:
Thanks a lot for your work:

```
Started TaskList: Setup Tasks
[x] - Updating package index
[x] - Updating package index: SUCCESS
[x] - Installing Node.js: 4.6.0
[x] - Installing Node.js: 4.6.0: SUCCESS
[x] - Setting up environment for meteor application
[x] - Setting up environment for meteor application: SUCCESS
[x] - Setting up shared bash functions
[x] - Setting up shared bash functions: SUCCESS
[x] - Copying MongoDB configuration
[x] - Copying MongoDB configuration: SUCCESS
[x] - Installing MongoDB
[x] - Installing MongoDB: SUCCESS
[x] - Configuring upstart: /etc/init/MeteorVPS.conf
[x] - Configuring upstart: /etc/init/MeteorVPS.conf: SUCCESS
[x] - Configuring systemd: /lib/systemd/system/MeteorVPS.service
[x] - Configuring systemd: /lib/systemd/system/MeteorVPS.service: SUC
```

**Comment by c9s** [comment] 2016-10-10 16:29
Thank you for your patience!

**Closed as completed** 2016-10-10 16:28 UTC
Labels: bug
